### ISSUE TITLE
./scripthunter.sh: line 110: jq: command not found

### ISSUE THREAD

**Issue by holoatomos** [robre/scripthunter#10]
When I run the following command I receive this error.
Command:
root@kali:~/Desktop/Tools/scripthunter#  ./scripthunter.sh https://EXAMPLE.com/

Error:
./scripthunter.sh: line 110: jq: command not found
[+] FFUF found 0 scripts in https://EXAMPLE.com/ ./ !
[*] Running FFUF on https://EXAMPLE.com/assets/

Dependents:
gau, ffuf, hakrawler, httpx, unfurl 
Work as intended on their own.

End result:
Scripthunter returns the results from the command into a file in the '/wordlists' folder called aggregated.txt  This file displays all of the JS File names in the TXT file. What I'm trying to figure out is why this error occurs and produce a result without errors. 

[Notes]
Before Error:

[*] Running GAU
[+] GAU found 86 scripts!
[*] Running hakrawler
[+] HAKRAWLER found 0 scripts!
[*] Found 45 directories containing .js files.
[*] Running FFUF on https://EXAMPLE.com/./

**Comment by geeknik** [comment]
Dis you install jq?

`apt install jq`

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.

**Comment by holoatomos** [comment]
Thank you, geeknik! It appears that I didn't install jq and your solution fixed the issue. Much appreciated.
