### ISSUE TITLE
hakrawler error in ubuntu(Elementory OS)

### ISSUE THREAD

**Issue by k4k4r07** [robre/scripthunter#9]
After running gau the tool states flag provided but not defined: -insecure and then prints help menu of hakrawler
![Screenshot from 2020-08-02 15-15-31](https://user-images.githubusercontent.com/51406427/89120335-214b6a80-d4d3-11ea-9ba1-0496ce830485.png)

**Comment by robre** [comment]
Update your hakrawler installation

**Comment by k4k4r07** [comment]
Done already!!!

**Comment by robre** [comment]
If you'd be on the latest hakrawler installation the -insecure flag would exist. Please recheck if you updated it correctly.

**Comment by k4k4r07** [comment]
Re-installed hakrawler and we are good to go!!!!!!!!!!!!!!!
Thanks for the amazing too.
